server:
  address: localhost
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/podologia_db?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 1234
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true

jwt_secret: 619E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG

