create table Category(
                     id int primary key generated BY DEFAULT AS IDENTITY ,
                     category_name varchar(100) unique not null ,
                     description varchar(550),
                     status varchar(20) default 'ACTIVE'
);